PRAGMA foreign_keys = ON;

-- SFEC V3: independent English Club information architecture.
UPDATE settings SET value_json='"https://sfec.skyfirst.io.vn"' WHERE key='app_url';
UPDATE settings SET value_json='"Học tiếng Anh. Kết nối cộng đồng. Vươn cao cùng SFEC."' WHERE key='hero_title';
UPDATE settings SET value_json='"Cổng học tập và hoạt động của The Sky First English Club."' WHERE key='hero_text';
UPDATE settings SET value_json='"/assets/sfec-logo.png"' WHERE key='hero_cover_url';
UPDATE settings SET value_json='"sfec.englishclub@gmail.com"' WHERE key='receiver_email';
UPDATE settings SET value_json='"sfec.vanphong@gmail.com"' WHERE key='support_email';

-- Remove forms copied from the network-level portal.
DELETE FROM forms WHERE id IN ('partner','project','unit','support','volunteer','class','core');

INSERT OR REPLACE INTO forms(id,name,prefix,description,audience,min_age,enabled,recipient_email,version,config_json) VALUES
('student','Đăng ký Học viên SFEC','SFEC-HV','Đăng ký tham gia các lớp học và chương trình tiếng Anh của SFEC.','public',NULL,1,'sfec.englishclub@gmail.com',3,
'{"id":"student","name":"Đăng ký Học viên SFEC","prefix":"SFEC-HV","description":"Đăng ký tham gia các lớp học và chương trình tiếng Anh của SFEC.","audience":"public","min_age":null,"term_codes":["PRIVACY/SFEC"],"sections":[{"title":"Thông tin học viên","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"dob","label":"Ngày sinh","type":"date","required":true},{"key":"email","label":"Email liên hệ","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":true},{"key":"school","label":"Trường/Lớp hiện tại","type":"text","required":false}]},{"title":"Lớp muốn tham gia","fields":[{"key":"course","label":"Lớp/Chương trình","type":"select","required":true,"options":["Lớp 9","Lớp 10","Lớp 11","Lớp 12","A1–A2","B1–B2","Tiếng Anh Giao tiếp","Từ vựng"]},{"key":"current_level","label":"Trình độ hiện tại","type":"textarea","required":true},{"key":"goal","label":"Mục tiêu học tập","type":"textarea","required":true},{"key":"schedule","label":"Khung thời gian có thể học","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"commit","label":"Tôi cam kết tham gia lớp nghiêm túc và tuân thủ quy định lớp học.","type":"checkbox","required":true},{"key":"privacy","label":"Tôi đã đọc Thông báo Quyền riêng tư SFEC.","type":"checkbox","required":true}]}]}'),
('teaching','Ứng tuyển TNV Dạy học SFEC','SFEC-GV','Dành cho giáo viên/TNV từ đủ 18 tuổi ứng tuyển giảng dạy hoặc trợ giảng.','public',18,1,'sfec.englishclub@gmail.com',3,
'{"id":"teaching","name":"Ứng tuyển TNV Dạy học SFEC","prefix":"SFEC-GV","description":"Dành cho giáo viên/TNV từ đủ 18 tuổi ứng tuyển giảng dạy hoặc trợ giảng.","audience":"public","min_age":18,"term_codes":["DK-03/2026/SFEC","PRIVACY/SFEC"],"sections":[{"title":"Thông tin ứng viên","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"dob","label":"Ngày sinh","type":"date","required":true},{"key":"email","label":"Email","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":true},{"key":"qualification","label":"Trình độ/chứng chỉ/năng lực tiếng Anh","type":"textarea","required":true},{"key":"experience","label":"Kinh nghiệm giảng dạy/trợ giảng","type":"textarea","required":true}]},{"title":"Phạm vi chuyên môn","fields":[{"key":"teaching_scope","label":"Lớp mong muốn phụ trách","type":"select","required":true,"options":["Lớp 9","Lớp 10","Lớp 11","Lớp 12","A1–A2","B1–B2","Tiếng Anh Giao tiếp","Từ vựng"]},{"key":"availability","label":"Khung thời gian có thể tham gia","type":"textarea","required":true},{"key":"lesson_prep","label":"Bạn chuẩn bị một buổi học như thế nào?","type":"textarea","required":true},{"key":"learner_support","label":"Bạn xử lý thế nào khi học viên không theo kịp bài?","type":"textarea","required":true},{"key":"minor_safety","label":"Bạn hiểu thế nào về việc bảo vệ người học chưa thành niên?","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"scope_confirm","label":"Tôi hiểu phạm vi giảng dạy phải được SFEC đánh giá và phê duyệt.","type":"checkbox","required":true},{"key":"truth","label":"Tôi xác nhận thông tin cung cấp là trung thực.","type":"checkbox","required":true}]}]}'),
('member','Đăng ký Thành viên SFEC','SFEC-TV','Dành cho cá nhân từ đủ 16 tuổi tham gia cộng đồng học thuật và hoạt động SFEC.','public',16,1,'sfec.englishclub@gmail.com',3,
'{"id":"member","name":"Đăng ký Thành viên SFEC","prefix":"SFEC-TV","description":"Dành cho cá nhân từ đủ 16 tuổi tham gia cộng đồng học thuật và hoạt động SFEC.","audience":"public","min_age":16,"term_codes":["PRIVACY/SFEC"],"sections":[{"title":"Thông tin cá nhân","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"dob","label":"Ngày sinh","type":"date","required":true},{"key":"email","label":"Email","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":true},{"key":"school","label":"Trường học/Đơn vị hiện tại","type":"text","required":false}]},{"title":"Tham gia SFEC","fields":[{"key":"interests","label":"Mảng hoạt động bạn quan tâm","type":"textarea","required":true},{"key":"skills","label":"Kỹ năng/Thế mạnh","type":"textarea","required":true},{"key":"why","label":"Vì sao bạn muốn trở thành Thành viên SFEC?","type":"textarea","required":true},{"key":"availability","label":"Thời gian có thể tham gia","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"truth","label":"Tôi xác nhận thông tin cung cấp là trung thực.","type":"checkbox","required":true},{"key":"privacy","label":"Tôi đã đọc Thông báo Quyền riêng tư SFEC.","type":"checkbox","required":true}]}]}'),
('core-content','Core Team — Ban Nội dung','SFEC-CORE-ND','Tuyển Core Team Ban Nội dung SFEC, từ đủ 18 tuổi.','public',18,1,'sfec.englishclub@gmail.com',3,
'{"id":"core-content","name":"Core Team — Ban Nội dung","prefix":"SFEC-CORE-ND","description":"Tuyển Core Team Ban Nội dung SFEC, từ đủ 18 tuổi.","audience":"public","min_age":18,"term_codes":["DK-01/2026/SFEC","PRIVACY/SFEC"],"sections":[{"title":"Hồ sơ ứng viên","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"dob","label":"Ngày sinh","type":"date","required":true},{"key":"email","label":"Email","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":true},{"key":"experience","label":"Kinh nghiệm học thuật/nội dung","type":"textarea","required":true},{"key":"strengths","label":"Thế mạnh nổi bật","type":"textarea","required":true},{"key":"why","label":"Vì sao bạn phù hợp với Ban Nội dung SFEC?","type":"textarea","required":true},{"key":"availability","label":"Thời gian có thể tham gia mỗi tuần","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"terms","label":"Tôi đã đọc và đồng ý với DK-01/2026/SFEC.","type":"checkbox","required":true},{"key":"truth","label":"Tôi xác nhận thông tin là trung thực.","type":"checkbox","required":true}]}]}'),
('core-comms','Core Team — Ban Truyền thông','SFEC-CORE-TT','Tuyển Core Team Ban Truyền thông SFEC, từ đủ 18 tuổi.','public',18,1,'sfec.englishclub@gmail.com',3,
'{"id":"core-comms","name":"Core Team — Ban Truyền thông","prefix":"SFEC-CORE-TT","description":"Tuyển Core Team Ban Truyền thông SFEC, từ đủ 18 tuổi.","audience":"public","min_age":18,"term_codes":["DK-01/2026/SFEC","PRIVACY/SFEC"],"sections":[{"title":"Hồ sơ ứng viên","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"dob","label":"Ngày sinh","type":"date","required":true},{"key":"email","label":"Email","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":true},{"key":"experience","label":"Kinh nghiệm truyền thông/thiết kế/nội dung","type":"textarea","required":true},{"key":"tools","label":"Công cụ/phần mềm có thể sử dụng","type":"textarea","required":true},{"key":"portfolio","label":"Portfolio/Minh chứng","type":"file","required":false,"accept":["application/pdf","image/png","image/jpeg"]},{"key":"why","label":"Vì sao bạn phù hợp với Ban Truyền thông SFEC?","type":"textarea","required":true},{"key":"availability","label":"Thời gian có thể tham gia mỗi tuần","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"terms","label":"Tôi đã đọc và đồng ý với DK-01/2026/SFEC.","type":"checkbox","required":true},{"key":"truth","label":"Tôi xác nhận thông tin là trung thực.","type":"checkbox","required":true}]}]}'),
('advisor','Đăng ký/Đề cử Cố vấn SFEC','SFEC-CV','Hồ sơ dành cho cố vấn chuyên môn hoặc cố vấn theo phạm vi hoạt động của SFEC.','public',NULL,1,'sfec.englishclub@gmail.com',3,
'{"id":"advisor","name":"Đăng ký/Đề cử Cố vấn SFEC","prefix":"SFEC-CV","description":"Hồ sơ dành cho cố vấn chuyên môn hoặc cố vấn theo phạm vi hoạt động của SFEC.","audience":"public","min_age":null,"term_codes":["PRIVACY/SFEC"],"sections":[{"title":"Thông tin cố vấn","fields":[{"key":"full_name","label":"Họ và tên","type":"text","required":true},{"key":"email","label":"Email","type":"email","required":true},{"key":"phone","label":"Số điện thoại/Zalo","type":"text","required":false},{"key":"organization","label":"Đơn vị/Cơ quan hiện tại","type":"text","required":false},{"key":"expertise","label":"Lĩnh vực chuyên môn","type":"textarea","required":true},{"key":"experience","label":"Kinh nghiệm liên quan","type":"textarea","required":true},{"key":"scope","label":"Phạm vi có thể cố vấn cho SFEC","type":"textarea","required":true}]},{"title":"Xác nhận","fields":[{"key":"truth","label":"Tôi xác nhận thông tin cung cấp là trung thực.","type":"checkbox","required":true},{"key":"privacy","label":"Tôi đã đọc Thông báo Quyền riêng tư SFEC.","type":"checkbox","required":true}]}]}');

-- Replace copied class catalog. No IELTS in SFEC catalog.
DELETE FROM classes WHERE unit_code='SFEC';
INSERT INTO classes(id,unit_code,title,level,status,schedule_json,data_json) VALUES
('SFEC-L9','SFEC','Tiếng Anh Lớp 9','Lớp 9','Đang mở đăng ký','{}','{}'),
('SFEC-L10','SFEC','Tiếng Anh Lớp 10','Lớp 10','Chuẩn bị mở','{}','{}'),
('SFEC-L11','SFEC','Tiếng Anh Lớp 11','Lớp 11','Chuẩn bị mở','{}','{}'),
('SFEC-L12','SFEC','Tiếng Anh Lớp 12','Lớp 12','Đang mở đăng ký','{}','{}'),
('SFEC-A1A2','SFEC','Tiếng Anh A1–A2','A1–A2','Đang mở đăng ký','{}','{}'),
('SFEC-B1B2','SFEC','Tiếng Anh B1–B2','B1–B2','Đang mở đăng ký','{}','{}'),
('SFEC-COMM','SFEC','Tiếng Anh Giao tiếp','Giao tiếp','Chuẩn bị mở','{}','{}'),
('SFEC-VOCAB','SFEC','Từ vựng tiếng Anh','Từ vựng','Chuẩn bị mở','{}','{}');

-- SFEC-specific role labels.
INSERT OR IGNORE INTO roles(id,name,level,description) VALUES('content_core','Core Ban Nội dung',60,'Học liệu, nội dung học thuật và chất lượng chương trình SFEC.');
INSERT OR IGNORE INTO roles(id,name,level,description) VALUES('advisor','Cố vấn SFEC',55,'Cố vấn chuyên môn theo phạm vi được giao.');
UPDATE roles SET name='Core Ban Truyền thông',description='Truyền thông, thiết kế và nội dung kênh SFEC.' WHERE id='communications';
UPDATE roles SET name='TNV Dạy học',description='Tình nguyện viên giảng dạy/trợ giảng theo phạm vi chuyên môn được phê duyệt.' WHERE id='volunteer';

-- Disable network-level modules that are not part of the SFEC public/product model.
UPDATE modules SET enabled=0 WHERE key IN ('units');
UPDATE modules SET name='Học viên & Thành viên',description='Hồ sơ học viên, thành viên và quá trình tham gia SFEC.' WHERE key='people';
UPDATE modules SET name='TNV Dạy học',description='Ứng tuyển, đánh giá và phạm vi giảng dạy/trợ giảng.' WHERE key='volunteer_teaching';

UPDATE news SET body='Cổng SFEC tập trung vào lớp học, học viên, thành viên, TNV Dạy học, Core Team và hoạt động học thuật của The Sky First English Club.' WHERE id='NEWS-WELCOME';
DELETE FROM news WHERE id='NEWS-CORE-2026';
INSERT OR REPLACE INTO news(id,title,slug,body,status,published_at) VALUES('NEWS-SFEC-ECOSYSTEM','SFEC — một không gian học tiếng Anh và phát triển cùng nhau','sfec-english-learning-community','Khám phá lớp học, hoạt động học thuật và các cơ hội tham gia đội ngũ SFEC.','published',CURRENT_TIMESTAMP);

UPDATE email_templates SET subject_template='[SFEC] Đã tiếp nhận đăng ký {{code}} — {{form_name}}' WHERE key='submission_confirmation';
INSERT OR REPLACE INTO meta(key,value) VALUES('sfec_product_version','3');
