-- SFEC email automation coverage expansion. Additive only; apply after migrations 0001-0010.
INSERT OR IGNORE INTO email_templates(key,subject_template,html_template,text_template,enabled) VALUES
('account_status','[SFEC] Cập nhật trạng thái tài khoản','<h2>Cập nhật tài khoản</h2><p>Xin chào {{full_name}},</p><p>Trạng thái tài khoản của bạn đã được cập nhật: <b>{{status}}</b>.</p><p>Nếu cần hỗ trợ, liên hệ sfec@skyfirst.io.vn.</p><p>Mạng lưới Giáo dục &amp; Phát triển Cộng đồng Sky First</p>','Xin chào {{full_name}}, trạng thái tài khoản: {{status}}. Hỗ trợ: sfec@skyfirst.io.vn.',1),
('role_updated','[SFEC] Cập nhật quyền tài khoản','<h2>Thông tin phân quyền</h2><p>Xin chào {{full_name}},</p><p>Quyền truy cập của tài khoản đã được quản trị viên cập nhật.</p><p>Vui lòng đăng nhập để xem quyền hiện tại. Nếu có thắc mắc, liên hệ sfec@skyfirst.io.vn.</p>','Quyền truy cập tài khoản đã được cập nhật. Liên hệ sfec@skyfirst.io.vn nếu cần hỗ trợ.',1),
('certificate_requested','[SFEC] Đã tiếp nhận đề nghị GCN/GXN {{reference}}','<h2>Đã tiếp nhận đề nghị</h2><p>Xin chào {{full_name}},</p><p>Đề nghị của bạn đã được tiếp nhận và đang chờ xử lý.</p><p>Mã tham chiếu: {{reference}}</p><p>Lưu ý: thông báo này không đồng nghĩa GCN/GXN đã được cấp.</p>','Đề nghị GCN/GXN đã được tiếp nhận, mã {{reference}}. Đây không phải xác nhận đã cấp.',1),
('certificate_status','[SFEC] Cập nhật trạng thái đề nghị GCN/GXN {{reference}}','<h2>Cập nhật trạng thái đề nghị</h2><p>Xin chào {{full_name}},</p><p>Mã tham chiếu: {{reference}}</p><p>Trạng thái: <b>{{status}}</b></p><p>Ghi chú: {{note}}</p><p>Thông tin cấp phát chính thức phải được xác nhận từ đơn vị có thẩm quyền.</p>','Mã {{reference}}. Trạng thái: {{status}}. Ghi chú: {{note}}. Thông báo không thay thế xác minh chính thức.',1),
('approval_status','[SFEC] Cập nhật quyết định phê duyệt {{reference}}','<h2>Cập nhật quyết định</h2><p>Xin chào {{full_name}},</p><p>Yêu cầu: {{action}}</p><p>Trạng thái: <b>{{status}}</b></p><p>Ghi chú: {{note}}</p>','Yêu cầu {{action}} có trạng thái {{status}}. Ghi chú: {{note}}.',1),
('privacy_request_status','[SFEC] Cập nhật yêu cầu quyền riêng tư {{reference}}','<h2>Cập nhật yêu cầu quyền riêng tư</h2><p>Xin chào {{full_name}},</p><p>Mã yêu cầu: {{reference}}</p><p>Trạng thái: {{status}}</p><p>Ghi chú: {{note}}</p>','Yêu cầu {{reference}}: {{status}}. {{note}}',1),
('person_added','[SFEC] Hồ sơ thành viên đã được tiếp nhận','<h2>Hồ sơ thành viên</h2><p>Xin chào {{full_name}},</p><p>Hệ thống đã liên kết hồ sơ của bạn với hồ sơ thành viên SFEC.</p><p>Thông tin được xử lý theo quyền truy cập và chính sách dữ liệu của hệ thống.</p>','Hồ sơ của bạn đã được liên kết với hồ sơ thành viên SFEC.',1);
